// This file is automatically generated by the Python script and should not be modified manually.
#define PYBIND11_DETAILED_ERROR_MESSAGES

#include "A_utils.hpp"
#include "B_bind_Vector.hpp"
#include "C_bind_Rect.hpp"
#include "D_bind_Matrix.hpp"
#include "Graphics/bind_CoordinateType.hpp"
#include "Graphics/bind_BlendMode.hpp"
#include "Window/bind_Sensor.hpp"
#include "Audio/bind_SoundChannel.hpp"
#include "Audio/bind_PlaybackDevice.hpp"
#include "System/bind_Angle.hpp"
#include "Graphics/bind_PrimitiveType.hpp"
#include "Window/bind_ContextSettings.hpp"
#include "System/bind_String.hpp"
#include "Graphics/bind_Color.hpp"
#include "System/bind_InputStream.hpp"
#include "Network/bind_Packet.hpp"
#include "Window/bind_WindowHandle.hpp"
#include "Window/bind_WindowEnums.hpp"
#include "Network/bind_Socket.hpp"
#include "Graphics/bind_StencilMode.hpp"
#include "System/bind_Time.hpp"
#include "Audio/bind_SoundRecorder.hpp"
#include "Audio/bind_SoundFileReader.hpp"
#include "Audio/bind_SoundFileWriter.hpp"
#include "Graphics/bind_Transform.hpp"
#include "Window/bind_Cursor.hpp"
#include "Window/bind_Context.hpp"
#include "Audio/bind_SoundSource.hpp"
#include "Graphics/bind_Glyph.hpp"
#include "Window/bind_VideoMode.hpp"
#include "Audio/bind_Listener.hpp"
#include "Window/bind_Touch.hpp"
#include "Window/bind_Mouse.hpp"
#include "Window/bind_Joystick.hpp"
#include "Window/bind_Clipboard.hpp"
#include "Window/bind_Keyboard.hpp"
#include "Graphics/bind_Shader.hpp"
#include "Graphics/bind_Image.hpp"
#include "Graphics/bind_Vertex.hpp"
#include "System/bind_MemoryInputStream.hpp"
#include "System/bind_FileInputStream.hpp"
#include "Audio/bind_SoundBuffer.hpp"
#include "System/bind_Sleep.hpp"
#include "System/bind_Clock.hpp"
#include "Network/bind_SocketSelector.hpp"
#include "Network/bind_IpAddress.hpp"
#include "Audio/bind_InputSoundFile.hpp"
#include "Audio/bind_OutputSoundFile.hpp"
#include "Graphics/bind_Transformable.hpp"
#include "Graphics/bind_View.hpp"
#include "Graphics/bind_RenderStates.hpp"
#include "Audio/bind_SoundStream.hpp"
#include "Audio/bind_Sound.hpp"
#include "Window/bind_Event.hpp"
#include "Graphics/bind_Texture.hpp"
#include "Audio/bind_SoundBufferRecorder.hpp"
#include "Network/bind_UdpSocket.hpp"
#include "Network/bind_TcpSocket.hpp"
#include "Network/bind_TcpListener.hpp"
#include "Graphics/bind_RenderTarget.hpp"
#include "Graphics/bind_Drawable.hpp"
#include "Audio/bind_Music.hpp"
#include "Window/bind_WindowBase.hpp"
#include "Graphics/bind_Font.hpp"
#include "Network/bind_Ftp.hpp"
#include "Network/bind_Http.hpp"
#include "Graphics/bind_RenderTexture.hpp"
#include "Graphics/bind_VertexArray.hpp"
#include "Graphics/bind_VertexBuffer.hpp"
#include "Graphics/bind_Sprite.hpp"
#include "Window/bind_Window.hpp"
#include "Graphics/bind_Shape.hpp"
#include "Graphics/bind_Text.hpp"
#include "Graphics/bind_RenderWindow.hpp"
#include "Graphics/bind_CircleShape.hpp"
#include "Graphics/bind_ConvexShape.hpp"
#include "Graphics/bind_RectangleShape.hpp"

PYBIND11_MODULE(pysf, m) {
    m.doc() = "SFML Library";

    B_bind_Vector(m);
    C_bind_Rect(m);
    D_bind_Matrix(m);
    bind_CoordinateType(m);
    bind_BlendMode(m);
    bind_Sensor(m);
    bind_SoundChannel(m);
    bind_PlaybackDevice(m);
    bind_Angle(m);
    bind_PrimitiveType(m);
    bind_ContextSettings(m);
    bind_String(m);
    bind_Color(m);
    bind_InputStream(m);
    bind_Packet(m);
    bind_WindowHandle(m);
    bind_WindowEnums(m);
    bind_Socket(m);
    bind_StencilMode(m);
    bind_Time(m);
    bind_SoundRecorder(m);
    bind_SoundFileReader(m);
    bind_SoundFileWriter(m);
    bind_Transform(m);
    bind_Cursor(m);
    bind_Context(m);
    bind_SoundSource(m);
    bind_Glyph(m);
    bind_VideoMode(m);
    bind_Listener(m);
    bind_Touch(m);
    bind_Mouse(m);
    bind_Joystick(m);
    bind_Clipboard(m);
    bind_Keyboard(m);
    bind_Shader(m);
    bind_Image(m);
    bind_Vertex(m);
    bind_MemoryInputStream(m);
    bind_FileInputStream(m);
    bind_SoundBuffer(m);
    bind_Sleep(m);
    bind_Clock(m);
    bind_SocketSelector(m);
    bind_IpAddress(m);
    bind_InputSoundFile(m);
    bind_OutputSoundFile(m);
    bind_Transformable(m);
    bind_View(m);
    bind_RenderStates(m);
    bind_SoundStream(m);
    bind_Sound(m);
    bind_Event(m);
    bind_Texture(m);
    bind_SoundBufferRecorder(m);
    bind_UdpSocket(m);
    bind_TcpSocket(m);
    bind_TcpListener(m);
    bind_RenderTarget(m);
    bind_Drawable(m);
    bind_Music(m);
    bind_WindowBase(m);
    bind_Font(m);
    bind_Ftp(m);
    bind_Http(m);
    bind_RenderTexture(m);
    bind_VertexArray(m);
    bind_VertexBuffer(m);
    bind_Sprite(m);
    bind_Window(m);
    bind_Shape(m);
    bind_Text(m);
    bind_RenderWindow(m);
    bind_CircleShape(m);
    bind_ConvexShape(m);
    bind_RectangleShape(m);
}
