// This file is automatically generated by the Python script and should not be modified manually.

#include "A_utils.hpp"
#include "B_bind_Vector.hpp"
#include "C_bind_Rect.hpp"
#include "D_bind_Matrix.hpp"
#include "Graphics/bind_BlendMode.hpp"
#include "Graphics/bind_StencilMode.hpp"
#include "System/bind_InputStream.hpp"
#include "Graphics/bind_PrimitiveType.hpp"
#include "Network/bind_Socket.hpp"
#include "Network/bind_Packet.hpp"
#include "System/bind_Angle.hpp"
#include "Window/bind_WindowHandle.hpp"
#include "System/bind_Time.hpp"
#include "Window/bind_Sensor.hpp"
#include "Graphics/bind_Color.hpp"
#include "System/bind_String.hpp"
#include "Audio/bind_PlaybackDevice.hpp"
#include "Window/bind_ContextSettings.hpp"
#include "Audio/bind_SoundChannel.hpp"
#include "Window/bind_WindowEnums.hpp"
#include "Graphics/bind_CoordinateType.hpp"
#include "System/bind_FileInputStream.hpp"
#include "System/bind_MemoryInputStream.hpp"
#include "Window/bind_Cursor.hpp"
#include "Graphics/bind_Glyph.hpp"
#include "Window/bind_Mouse.hpp"
#include "Window/bind_VideoMode.hpp"
#include "Graphics/bind_Transform.hpp"
#include "Audio/bind_SoundSource.hpp"
#include "Window/bind_Context.hpp"
#include "Window/bind_Touch.hpp"
#include "Audio/bind_Listener.hpp"
#include "Network/bind_IpAddress.hpp"
#include "Network/bind_SocketSelector.hpp"
#include "System/bind_Sleep.hpp"
#include "System/bind_Clock.hpp"
#include "Graphics/bind_Shader.hpp"
#include "Graphics/bind_Image.hpp"
#include "Graphics/bind_Vertex.hpp"
#include "Window/bind_Keyboard.hpp"
#include "Window/bind_Clipboard.hpp"
#include "Window/bind_Joystick.hpp"
#include "Audio/bind_SoundBuffer.hpp"
#include "Audio/bind_SoundFileWriter.hpp"
#include "Audio/bind_SoundFileReader.hpp"
#include "Audio/bind_SoundRecorder.hpp"
#include "Graphics/bind_Transformable.hpp"
#include "Graphics/bind_View.hpp"
#include "Graphics/bind_RenderStates.hpp"
#include "Audio/bind_SoundStream.hpp"
#include "Audio/bind_Sound.hpp"
#include "Network/bind_TcpListener.hpp"
#include "Network/bind_TcpSocket.hpp"
#include "Network/bind_UdpSocket.hpp"
#include "Graphics/bind_Texture.hpp"
#include "Window/bind_Event.hpp"
#include "Audio/bind_OutputSoundFile.hpp"
#include "Audio/bind_InputSoundFile.hpp"
#include "Audio/bind_SoundBufferRecorder.hpp"
#include "Graphics/bind_RenderTarget.hpp"
#include "Graphics/bind_Drawable.hpp"
#include "Audio/bind_Music.hpp"
#include "Network/bind_Ftp.hpp"
#include "Network/bind_Http.hpp"
#include "Graphics/bind_Font.hpp"
#include "Window/bind_WindowBase.hpp"
#include "Graphics/bind_RenderTexture.hpp"
#include "Graphics/bind_VertexBuffer.hpp"
#include "Graphics/bind_VertexArray.hpp"
#include "Graphics/bind_Sprite.hpp"
#include "Window/bind_Window.hpp"
#include "Graphics/bind_Shape.hpp"
#include "Graphics/bind_Text.hpp"
#include "Graphics/bind_RenderWindow.hpp"
#include "Graphics/bind_ConvexShape.hpp"
#include "Graphics/bind_RectangleShape.hpp"
#include "Graphics/bind_CircleShape.hpp"

PYBIND11_MODULE(pysf, m) {
    m.doc() = "SFML Library";

    auto m_sf = m.def_submodule("sf");
    B_bind_Vector(m_sf);
    C_bind_Rect(m_sf);
    D_bind_Matrix(m_sf);
    bind_BlendMode(m_sf);
    bind_StencilMode(m_sf);
    bind_InputStream(m_sf);
    bind_PrimitiveType(m_sf);
    bind_Socket(m_sf);
    bind_Packet(m_sf);
    bind_Angle(m_sf);
    bind_WindowHandle(m_sf);
    bind_Time(m_sf);
    bind_Sensor(m_sf);
    bind_Color(m_sf);
    bind_String(m_sf);
    bind_PlaybackDevice(m_sf);
    bind_ContextSettings(m_sf);
    bind_SoundChannel(m_sf);
    bind_WindowEnums(m_sf);
    bind_CoordinateType(m_sf);
    bind_FileInputStream(m_sf);
    bind_MemoryInputStream(m_sf);
    bind_Cursor(m_sf);
    bind_Glyph(m_sf);
    bind_Mouse(m_sf);
    bind_VideoMode(m_sf);
    bind_Transform(m_sf);
    bind_SoundSource(m_sf);
    bind_Context(m_sf);
    bind_Touch(m_sf);
    bind_Listener(m_sf);
    bind_IpAddress(m_sf);
    bind_SocketSelector(m_sf);
    bind_Sleep(m_sf);
    bind_Clock(m_sf);
    bind_Shader(m_sf);
    bind_Image(m_sf);
    bind_Vertex(m_sf);
    bind_Keyboard(m_sf);
    bind_Clipboard(m_sf);
    bind_Joystick(m_sf);
    bind_SoundBuffer(m_sf);
    bind_SoundFileWriter(m_sf);
    bind_SoundFileReader(m_sf);
    bind_SoundRecorder(m_sf);
    bind_Transformable(m_sf);
    bind_View(m_sf);
    bind_RenderStates(m_sf);
    bind_SoundStream(m_sf);
    bind_Sound(m_sf);
    bind_TcpListener(m_sf);
    bind_TcpSocket(m_sf);
    bind_UdpSocket(m_sf);
    bind_Texture(m_sf);
    bind_Event(m_sf);
    bind_OutputSoundFile(m_sf);
    bind_InputSoundFile(m_sf);
    bind_SoundBufferRecorder(m_sf);
    bind_RenderTarget(m_sf);
    bind_Drawable(m_sf);
    bind_Music(m_sf);
    bind_Ftp(m_sf);
    bind_Http(m_sf);
    bind_Font(m_sf);
    bind_WindowBase(m_sf);
    bind_RenderTexture(m_sf);
    bind_VertexBuffer(m_sf);
    bind_VertexArray(m_sf);
    bind_Sprite(m_sf);
    bind_Window(m_sf);
    bind_Shape(m_sf);
    bind_Text(m_sf);
    bind_RenderWindow(m_sf);
    bind_ConvexShape(m_sf);
    bind_RectangleShape(m_sf);
    bind_CircleShape(m_sf);
}
