import os
import platform
from pathlib import Path
from ctypes.util import find_library
import clang.cindex
from .hppParser import Parser
from .bindingGenerator import Generator
from .hppSorter import Sorter
from .utils import scan_hpp_files


__all__ = ["Parser", "Generator"]
__version__ = "1.0.0"
__author__ = "JasonLeon"
__copyright__ = "Copyright (c) 2026, JasonLeon"
__license__ = "MIT"

clang.cindex.Config.set_library_file(find_library("libclang"))
MAIN_DOC = "\
This is an SFML binding library for Python.\\n\
It provides a set of Python bindings for the SFML library.\\n\
The bindings are generated using the pybind11 library.\\n\
\\n\
SFML is multi-media\\n\
SFML provides a simple interface to the various components of your PC, to ease the development of games and multimedia applications. It is composed of five modules: system, window, graphics, audio and network.\\n\
\\n\
SFML is multi-platform\\n\
With SFML, your application can compile and run out of the box on the most common operating systems: Windows, Linux, macOS and Android & iOS (with limitations).\\n\
"


def generate_binding_from_hpp(
    common_module_name,
    hpp_root,
    hpp_file,
    output_file,
    includes,
    cpp_version,
    ignored_macros,
    REPLACE_TYPE,
    SPECIFIC_TYPE,
    IGNORE_TYPE,
    IGNORE_RETURN_TYPE,
    SPECIFIC_RETURN_TYPE,
    REPLACE_DEFAULT,
    IGNORED_MODULE,
    SPECIAL_REPLACE,
    READWRITE_IGNORE,
):
    parser = Parser(includes, hpp_root, hpp_file, cpp_version, ignored_macros)
    items = parser.get_dict()
    generator = Generator(
        common_module_name,
        items,
        REPLACE_TYPE,
        SPECIFIC_TYPE,
        IGNORE_TYPE,
        IGNORE_RETURN_TYPE,
        SPECIFIC_RETURN_TYPE,
        REPLACE_DEFAULT,
        IGNORED_MODULE,
        SPECIAL_REPLACE,
        READWRITE_IGNORE,
        hpp_file,
    )
    generator.emit_pybind_module(output_file)


def generate_hpp_file_from_hpp(
    read_file,
    hpp_file,
    output_file,
):
    with open(output_file, "w", encoding="utf-8") as f:
        file_names = Path(read_file).parts[-3:]
        real_include = "/".join(file_names)
        f.write(f'#include "{real_include}"\n')
        f.write(f'#include "utils.hpp"\n')
        f.write("namespace py = pybind11;\n\n")
        f.write(f"void bind_{hpp_file.split('.')[0]}(py::module &m); \n")
    print(f"Generated {output_file}")


def generate_pybind_main(source_files, output_filename):
    try:
        with open(output_filename, "w", encoding="utf-8") as f:
            f.write(
                "// This file is automatically generated by the Python script and should not be modified manually.\n\n"
            )
            f.write('#define PYBIND11_INTERNALS_ID "PYSF"\n\n')
            f.write("#include <iostream>\n")
            for filename in source_files:
                f.write(f'#include "{filename}"\n')
            f.write("\n")

            f.write("PYBIND11_MODULE(pysf, m) {\n")
            f.write(f'    m.doc() = "{MAIN_DOC}";\n\n')

            f.write("    void *internals_ptr = static_cast<void *>(\n")
            f.write("        const_cast<py::detail::internals *>(&py::detail::get_internals()));\n")
            f.write('    std::cout << "[PYSF Binding] PyBind11 internals address: " << internals_ptr << std::endl;\n\n')

            for filename in source_files:
                if not "bind_" in filename:
                    continue

                base_name = Path(filename).name.split(".")[0]
                f.write(f"    {base_name}(m);\n")

            f.write("}\n")

        print(f"Generated {output_filename}")
    except IOError as e:
        print(f"Error writing to {output_filename}: {e}")
    except Exception as e:
        print(f"An unexpected error occurred when generating {output_filename}: {e}")


def generate_cmakelists(source_files, self_files, python_version):
    output_filename = "CMakeLists.txt"
    try:
        sources = ""
        for filename in source_files:
            flag = False
            for self_file in self_files:
                if filename in self_file:
                    flag = True
                    break
            if flag:
                sources += f'    "src/{filename.split(".")[0]}.cpp"\n'
                if platform.system() == "Darwin" and os.path.exists(f'src/{filename.split(".")[0]}.mm'):
                    sources += f'    "src/{filename.split(".")[0]}.mm"\n'
            else:
                sources += f'    "output/src/{filename.split(".")[0]}.cpp"\n'

        with open(f"{output_filename}.in", encoding="utf-8") as template, open(
            output_filename, "w", encoding="utf-8"
        ) as out:
            cmake_content = template.read().format(sources=sources, python_version=python_version)
            out.write(cmake_content)

        print(f"CMakeLists.txt generated successfully: {output_filename}")

    except IOError as e:
        print(f"Error writing to {output_filename}: {e}")
    except Exception as e:
        print(f"An unexpected error occurred when generating {output_filename}: {e}")
